# Generated by Django 5.1.5 on 2025-04-04 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='exenta_baja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='responsable',
            name='usuario',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
